# https://docs.docker.com/compose/compose-file/
name: public-wiki

services:

  web:
    container_name: web
    depends_on:
      - db
    build:
      context: .
    links:
      - db
    env_file:
      - .env
    init: true
    ports:
      - '8080:80'
    restart: on-failure
    security_opt:
      # For compatibility with Northflank
      - no-new-privileges:true
    volumes:
      # MediaWiki volume
      - volume-wiki:/mnt/wiki

  db:
    container_name: db
    # https://hub.docker.com/_/mysql/
    image: mysql
    env_file:
      - .env
    restart: on-failure
    volumes:
      # Configuration (read-only)
      - ../config/db.cnf:/etc/mysql/conf.d/db.cnf:ro
      # Data
      - volume-mysql:/var/lib/mysql

volumes:
  volume-mysql:
  volume-wiki:
