# https://docs.docker.com/compose/compose-file/

services:

  web:
    container_name: web
    depends_on:
      - db
    build:
      args:
        MW_VERSION: ${MW_VERSION}
      context: .
    links:
      - db
    env_file:
      - .env
    init: true
    ports:
      - '8080:80'
    restart: on-failure
    volumes:
      # Apache2 web server configuration
      - ./config/web-sites-available:/etc/apache2/sites-available:ro
      # media wiki volumes
      - public-wiki-vol-wiki:/var/www/wiki
      - public-wiki-vol-wiki-images:/var/www/wiki/images

  db:
    container_name: db
    # https://hub.docker.com/_/mariadb
    image: mariadb
    env_file:
      - .env
    restart: on-failure
    volumes:
      - public-wiki-vol-mysql:/var/lib/mysql

volumes:
  public-wiki-vol-mysql:
  public-wiki-vol-wiki:
  public-wiki-vol-wiki-images:
